//@flow
export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST';
export const ITEM_DETAILS_FAILURE = 'ITEM_DETAILS_FAILURE';
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS';

export const ITEM_IS_EDITED_REQUEST = 'ITEM_IS_EDITED_REQUEST';
