//@flow
export const ITEM_FORM_FIELD_REQUEST = 'ITEM_FORM_FIELD_REQUEST';
export const ITEM_FORM_FIELD_FAILURE = 'ITEM_FORM_FIELD_FAILURE';
export const ITEM_FORM_FIELD_SUCCESS = 'ITEM_FORM_FIELD_SUCCESS';

export const ITEM_IS_EDITED_REQUEST = 'ITEM_IS_EDITED_REQUEST';
