import { StyleSheet } from 'react-native';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3FEEE6',
    paddingVertical: 50,
    position: 'relative',
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  list: {
    paddingVertical: 5,
    margin: 3,
    flexDirection: 'row',
    backgroundColor: '#3FEEE6',
    justifyContent: 'flex-start',
    alignItems: 'center',
    zIndex: -1,
  },
  lightText: {
    color: '#000',
    width: 200,
    paddingLeft: 15,
    fontSize: 12,
  },
  line: {
    height: 0.5,
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  inputText: {
    alignSelf: 'stretch',
    fontSize: 18,
    height: 40,
    marginBottom: 30,
    color: '#000',
    borderBottomColor: '#rgba(255,255,255,0.5)',
    borderBottomWidth: 1,
    textAlign: 'center',
  },
  buttons: {
    paddingTop: 20,
    paddingBottom: 5,
    justifyContent: 'center',
    flexDirection: 'row',
    color: '#FFF',
  },
  title: {
    fontSize: 20,
    color: '#000',
    textAlign: 'center',
    marginBottom: 10,
  },
  button: {
    borderRadius: 15,
    width: '40%',
    backgroundColor: '#FC4445',
    paddingTop: 10,
    paddingBottom: 10,
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selected: { backgroundColor: '#FC4445' },
});
